# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NapoDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NapoDemo

  target 'NapoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
